[package]
name = "iron-gcd"
version = "0.1.0"
authors = ["davesabra <davesabra@yahoo.com>"]
edition = "2018"

[dependencies]
iron	=	"0.6.0"
router	=	"0.6.0"
urlencoded	=	"0.6.0"
media-types = "0.2.0"

